---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      connection: local
lint:
  name: yamllint
platforms:
  - name: local
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: macos
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
